# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parsers.tenhou.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_place', models.PositiveSmallIntegerField(choices=[(1, 'Real life game record'), (2, 'Tenhou game')], default=2)),
                ('game_rule', models.PositiveSmallIntegerField(choices=[[0, 'Unknown'], [1, 'Tonpusen. No tanyao, no red fives'], [2, 'Tonpusen. Tanyao, no red fives'], [3, 'Tonpusen. Tanyao, red fives'], [4, 'Tonpusen. Tanyao, red fives. Fast'], [5, 'Hanchan. No tanyao, no red fives'], [6, 'Hanchan. Tanyao, no red fives'], [7, 'Hanchan. Tanyao, red fives'], [8, 'Hanchan. Tanyao, red fives. Fast']], default=0)),
                ('game_type', models.PositiveSmallIntegerField(choices=[[0, 'Unknown'], [1, 'Standard game'], [2, 'Hirosima']], default=0)),
                ('lobby', models.PositiveSmallIntegerField(default=0)),
                ('game_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('game_log_content', models.TextField()),
                ('external_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('player_position', models.PositiveSmallIntegerField(default=0)),
                ('scores', models.IntegerField(default=0)),
                ('seat', models.PositiveSmallIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('rank', models.PositiveIntegerField(choices=[[0, '新人'], [1, '9級'], [2, '8級'], [3, '7級'], [4, '6級'], [5, '5級'], [6, '4級'], [7, '3級'], [8, '2級'], [9, '1級'], [10, '初段'], [11, '二段'], [12, '三段'], [13, '四段'], [14, '五段'], [15, '六段'], [16, '七段'], [17, '八段'], [18, '九段'], [19, '十段'], [20, '天鳳位']], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='accounts.Player')),
            ],
            options={
                'db_table': 'mahjong_game',
                'ordering': ['-game_date'],
            },
            bases=(models.Model, parsers.tenhou.constants.MahjongConstants),
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_win', models.BooleanField(default=False)),
                ('is_deal', models.BooleanField(default=False)),
                ('is_retake', models.BooleanField(default=False)),
                ('is_tsumo', models.BooleanField(default=False)),
                ('is_riichi', models.BooleanField(default=False)),
                ('is_open_hand', models.BooleanField(default=False)),
                ('is_damaten', models.BooleanField(default=False)),
                ('round_number', models.PositiveSmallIntegerField(default=0)),
                ('honba', models.PositiveSmallIntegerField(default=0)),
                ('win_scores', models.PositiveIntegerField(default=0)),
                ('lose_scores', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.Game')),
            ],
            options={
                'db_table': 'mahjong_game_round',
                'ordering': ['round_number', 'honba'],
            },
        ),
    ]
