# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Real life game record'), (1, 'Tenhou.net log')], default=1)),
                ('external_id', models.TextField(blank=True, default='', null=True)),
                ('player_position', models.PositiveSmallIntegerField(default=0)),
                ('scores', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='accounts.Player')),
            ],
            options={
                'db_table': 'mahjong_game',
                'ordering': ['-created_at'],
            },
        ),
    ]
