# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_rule',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Tonpu-sen. Ari, Ari.'), (1, 'Hanchan. Ari, Ari.')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Real life game record'), (1, 'Tenhou game')], default=1),
        ),
    ]
