# Generated by Django 3.1.2 on 2020-10-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201025_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='round_counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
