# Generated by Django 3.1.2 on 2020-10-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gameround_round_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='fu',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='han',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
