# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
