# Generated by Django 3.1.2 on 2020-11-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20201029_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_log_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
