# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_game_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='game_place',
        ),
    ]
