# Generated by Django 3.1.2 on 2020-11-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20201121_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_room',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
