# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20160524_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_win', models.BooleanField(default=False)),
                ('is_deal', models.BooleanField(default=False)),
                ('is_retake', models.BooleanField(default=False)),
                ('is_tsumo', models.BooleanField(default=False)),
                ('is_riichi', models.BooleanField(default=False)),
                ('is_open_hand', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.Game')),
            ],
            options={
                'db_table': 'mahjong_game_round',
                'ordering': ['-created_at'],
            },
        ),
    ]
