# Generated by Django 3.2 on 2021-04-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_game_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_room',
            field=models.PositiveSmallIntegerField(blank=True, choices=[[0, 'Unknown'], [1, '一般'], [2, '上級'], [3, '特上'], [4, '鳳凰']], default=None, null=True),
        ),
    ]
