# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gameround'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameround',
            options={'ordering': ['round_number', 'honba']},
        ),
        migrations.AddField(
            model_name='gameround',
            name='honba',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
