# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20160527_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='lose_scores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='win_scores',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
