# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20160527_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='is_damaten',
            field=models.BooleanField(default=False),
        ),
    ]
