# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_rule',
            field=models.PositiveSmallIntegerField(choices=[[0, 'Unknown'], [1, 'Tonpusen. No tanyao, no red fives'], [2, 'Tonpusen. Tanyao, no red fives'], [3, 'Tonpusen. Tanyao, red fives'], [4, 'Tonpusen. Tanyao, red fives. Fast'], [5, 'Hanchan. No tanyao, no red fives'], [6, 'Hanchan. Tanyao, no red fives'], [7, 'Hanchan. Tanyao, red fives'], [8, 'Hanchan. Tanyao, red fives. Fast']], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.PositiveSmallIntegerField(choices=[[0, 'Unknown'], [1, 'Standard game'], [2, 'Hirosima']], default=0),
        ),
    ]
