# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20170312_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='scores',
            field=models.IntegerField(default=0),
        ),
    ]
