# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160524_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lobby',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
