# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20160913_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rank',
            field=models.PositiveIntegerField(choices=[[0, '新人'], [1, '9級'], [2, '8級'], [3, '7級'], [4, '6級'], [5, '5級'], [6, '4級'], [7, '3級'], [8, '2級'], [9, '1級'], [10, '初段'], [11, '二段'], [12, '三段'], [13, '四段'], [14, '五段'], [15, '六段'], [16, '七段'], [17, '八段'], [18, '九段'], [19, '十段'], [20, '天鳳位']], default=0),
        ),
    ]
