# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('game_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mahjong_event_game',
            },
        ),
        migrations.CreateModel(
            name='EventPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_place', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sum_of_places', models.PositiveIntegerField(default=0)),
                ('played_games', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mahjong_event_player',
            },
        ),
        migrations.CreateModel(
            name='MahjongEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mahjong_event',
            },
        ),
        migrations.AddField(
            model_name='eventplayer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.MahjongEvent'),
        ),
        migrations.AddField(
            model_name='eventplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Player'),
        ),
        migrations.AddField(
            model_name='eventgame',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.MahjongEvent'),
        ),
    ]
